version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5433" # use port that you want to in your local instead of 5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db:
